name: Hello World
on:
  push:
    branches:
      - main
jobs:
   first-hello-world-job:
      run-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v3
         - name: Print message
           run: echo "hello world GA testing"
